// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: storage-node.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FreeStorage int32 `protobuf:"varint,1,opt,name=freeStorage,proto3" json:"freeStorage,omitempty"` // in bytes
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_node_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_node_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_storage_node_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatsResponse) GetFreeStorage() int32 {
	if x != nil {
		return x.FreeStorage
	}
	return 0
}

type InitTransactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileSize      int64  `protobuf:"varint,1,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	SegmentsCount int32  `protobuf:"varint,2,opt,name=segmentsCount,proto3" json:"segmentsCount,omitempty"`
	FileHash      string `protobuf:"bytes,3,opt,name=fileHash,proto3" json:"fileHash,omitempty"` // hex-encoded hash
	Bid           int64  `protobuf:"varint,4,opt,name=bid,proto3" json:"bid,omitempty"`
	Timeperiod    int64  `protobuf:"varint,5,opt,name=timeperiod,proto3" json:"timeperiod,omitempty"`
}

func (x *InitTransactionRequest) Reset() {
	*x = InitTransactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_node_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitTransactionRequest) ProtoMessage() {}

func (x *InitTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_node_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitTransactionRequest.ProtoReflect.Descriptor instead.
func (*InitTransactionRequest) Descriptor() ([]byte, []int) {
	return file_storage_node_proto_rawDescGZIP(), []int{1}
}

func (x *InitTransactionRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *InitTransactionRequest) GetSegmentsCount() int32 {
	if x != nil {
		return x.SegmentsCount
	}
	return 0
}

func (x *InitTransactionRequest) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *InitTransactionRequest) GetBid() int64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *InitTransactionRequest) GetTimeperiod() int64 {
	if x != nil {
		return x.Timeperiod
	}
	return 0
}

type InitTransactionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JWT       string `protobuf:"bytes,1,opt,name=JWT,proto3" json:"JWT,omitempty"`
	ExpiresAt int64  `protobuf:"varint,2,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
}

func (x *InitTransactionResponse) Reset() {
	*x = InitTransactionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_node_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitTransactionResponse) ProtoMessage() {}

func (x *InitTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_node_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitTransactionResponse.ProtoReflect.Descriptor instead.
func (*InitTransactionResponse) Descriptor() ([]byte, []int) {
	return file_storage_node_proto_rawDescGZIP(), []int{2}
}

func (x *InitTransactionResponse) GetJWT() string {
	if x != nil {
		return x.JWT
	}
	return ""
}

func (x *InitTransactionResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_node_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_storage_node_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_storage_node_proto_rawDescGZIP(), []int{3}
}

var File_storage_node_proto protoreflect.FileDescriptor

var file_storage_node_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2d, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x66, 0x72, 0x65, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x66, 0x72, 0x65, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x22, 0xa8, 0x01, 0x0a, 0x16, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0d, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x48, 0x61, 0x73, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x62, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x74, 0x69, 0x6d, 0x65, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x22, 0x49, 0x0a, 0x17,
	0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4a, 0x57, 0x54, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4a, 0x57, 0x54, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x32, 0x96, 0x01, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x33, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x0c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0f, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_storage_node_proto_rawDescOnce sync.Once
	file_storage_node_proto_rawDescData = file_storage_node_proto_rawDesc
)

func file_storage_node_proto_rawDescGZIP() []byte {
	file_storage_node_proto_rawDescOnce.Do(func() {
		file_storage_node_proto_rawDescData = protoimpl.X.CompressGZIP(file_storage_node_proto_rawDescData)
	})
	return file_storage_node_proto_rawDescData
}

var file_storage_node_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_storage_node_proto_goTypes = []interface{}{
	(*GetStatsResponse)(nil),        // 0: proto.GetStatsResponse
	(*InitTransactionRequest)(nil),  // 1: proto.InitTransactionRequest
	(*InitTransactionResponse)(nil), // 2: proto.InitTransactionResponse
	(*Empty)(nil),                   // 3: proto.Empty
}
var file_storage_node_proto_depIdxs = []int32{
	3, // 0: proto.StorageNode.GetStats:input_type -> proto.Empty
	1, // 1: proto.StorageNode.InitTransaction:input_type -> proto.InitTransactionRequest
	0, // 2: proto.StorageNode.GetStats:output_type -> proto.GetStatsResponse
	2, // 3: proto.StorageNode.InitTransaction:output_type -> proto.InitTransactionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_storage_node_proto_init() }
func file_storage_node_proto_init() {
	if File_storage_node_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_storage_node_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_node_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitTransactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_node_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitTransactionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_node_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storage_node_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_node_proto_goTypes,
		DependencyIndexes: file_storage_node_proto_depIdxs,
		MessageInfos:      file_storage_node_proto_msgTypes,
	}.Build()
	File_storage_node_proto = out.File
	file_storage_node_proto_rawDesc = nil
	file_storage_node_proto_goTypes = nil
	file_storage_node_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StorageNodeClient is the client API for StorageNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageNodeClient interface {
	GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetStatsResponse, error)
	InitTransaction(ctx context.Context, in *InitTransactionRequest, opts ...grpc.CallOption) (*InitTransactionResponse, error)
}

type storageNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageNodeClient(cc grpc.ClientConnInterface) StorageNodeClient {
	return &storageNodeClient{cc}
}

func (c *storageNodeClient) GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, "/proto.StorageNode/GetStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeClient) InitTransaction(ctx context.Context, in *InitTransactionRequest, opts ...grpc.CallOption) (*InitTransactionResponse, error) {
	out := new(InitTransactionResponse)
	err := c.cc.Invoke(ctx, "/proto.StorageNode/InitTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageNodeServer is the server API for StorageNode service.
type StorageNodeServer interface {
	GetStats(context.Context, *Empty) (*GetStatsResponse, error)
	InitTransaction(context.Context, *InitTransactionRequest) (*InitTransactionResponse, error)
}

// UnimplementedStorageNodeServer can be embedded to have forward compatible implementations.
type UnimplementedStorageNodeServer struct {
}

func (*UnimplementedStorageNodeServer) GetStats(context.Context, *Empty) (*GetStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (*UnimplementedStorageNodeServer) InitTransaction(context.Context, *InitTransactionRequest) (*InitTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitTransaction not implemented")
}

func RegisterStorageNodeServer(s *grpc.Server, srv StorageNodeServer) {
	s.RegisterService(&_StorageNode_serviceDesc, srv)
}

func _StorageNode_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StorageNode/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).GetStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNode_InitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).InitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StorageNode/InitTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).InitTransaction(ctx, req.(*InitTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StorageNode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StorageNode",
	HandlerType: (*StorageNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStats",
			Handler:    _StorageNode_GetStats_Handler,
		},
		{
			MethodName: "InitTransaction",
			Handler:    _StorageNode_InitTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage-node.proto",
}
